# Generated by Django 4.2.3 on 2023-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_tag_alter_article_options_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles_tag',
            options={'verbose_name': 'Тег'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
